export default [
  {title: 'PHP', value: 90},
  {title: 'JavaScript', value: 90},
  {title: 'Python', value: 60},
  {title: 'Laravel', value: 90},
  {title: 'Ruby on Rails', value: 80},
  {title: 'NodeJS', value: 80},
  {title: 'React', value: 90},
  {title: 'React Native', value: 80},
  {title: 'Angular', value: 80},
  {title: 'Magento 2', value: 87},
  {title: 'CodeIgniter', value: 90},
  {title: 'HTML', value: 95},
  {title: 'CSS', value: 95},
];