export default [
  { title: "PHP", value: 95 },
  { title: "Laravel", value: 95 },
  { title: "JavaScript", value: 90 },
  { title: "TypeScript", value: 90 },
  { title: "NodeJS", value: 90 },
  { title: "React", value: 90 },
  { title: "React Native", value: 80 },
  { title: "Magento 2", value: 87 },
  { title: "CodeIgniter", value: 90 },
  { title: "HTML", value: 95 },
  { title: "CSS", value: 95 },
  { title: "Collaboration", value: 95 },
  { title: "Project Management", value: 93 },
];
